fail_fast: false
default_language_version:
  python: python3.11

repos:
  # Conventional commit
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  # Words spelling
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args: [--skip='*.po']
        exclude: ^tests/
  # Pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # Generic checks
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: mixed-line-ending
      #
      - id: check-yaml
        exclude: ^tests/
      - id: check-json
        exclude: ^tests/
      - id: check-xml
        exclude: ^tests/
      - id: check-toml
        exclude: ^tests/
      # Python
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: debug-statements
      - id: name-tests-test
  # Bash
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
      - id: shell-lint
        args: [--format=json]
  # Python
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-no-eval
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.3
    hooks:
      - id: python-safety-dependencies-check
        stages: [manual]
        files: requirements
        args: ["--short-report"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.1
    hooks:
      - id: ruff
        args: ["--ignore=PLR0912,RUF100,T20,D,TD,FIX"]
      - id: ruff-format
  # PDM
  - repo: https://github.com/pdm-project/pdm
    rev: 2.15.0
    hooks:
      - id: pdm-lock-check
